import { Member } from '../types/members'

export const members: Member[] = [
  { name: "Alex Kim", title: "Member", image: "/favicon.svg" },
  { name: "Alp Senay", title: "Member", image: "/members/alp.jpg" },  
  { name: "Andrew Falcom", title: "Member", image: "/members/andrew.png" },  
  { name: "Angie Zhu", title: "Member", image: "/members/angie.png" },
  { name: "Ashley Huang", title: "Member", image: "/members/ashley.png" },
  { name: "Bonnie Wang", title: "Member", image: "/members/bonnie.png" },
  { name: "Brad Ma", title: "Member", image: "/members/brad.JPG" },
  { name: "Cathryn Chang", title: "Member", image: "/members/cathryn.jpeg" },
  { name: "Dylan Dang", title: "Project Manager", image: "/members/dylan.png" },
  { name: "Edan Gortzak", title: "Member", image: "/members/edan.png" },
  { name: "Evan Johnson", title: "Member", image: "/members/evan.png" },
  { name: "Jennifer Cheng", title: "Member", image: "/members/jennifer.jpeg" },
  { name: "Jesslyn Ashley Ruswan", title: "Member", image: "/members/jesslyn.jpeg" },
  { name: "Joey Wong", title: "Member", image: "/members/joey.png" },
  { name: "Julia Duan", title: "Member", image: "/members/julia.png" }, 
  { name: "Kathy Yun", title: "Member", image: "/members/kathy.jpeg" },
  { name: "Landy Manzanero", title: "Project Manager", image: "/members/landy.JPEG" },
  { name: "Lara Chieppe", title: "Project Manager", image: "/members/lara.jpg" },
  { name: "Mandy Pham", title: "Member", image: "/members/mandy.jpeg" },
  { name: "Maxine Tseng", title: "Member", image: "/members/maxine.jpeg" },
  { name: "Mike Guerrero", title: "Member", image: "/exec/mike.jpeg"},
  { name: "Naila Talib", title: "Member", image: "/members/naila.jpg" },
  { name: "Nathan Ye", title: "Member", image: "/members/nathan.jpeg" },
  { name: "Nomin-Erdene Batchuluun", title: "Member", image: "/members/nomi.jpeg" },
  { name: "Oscar Zhang", title: "Member", image: "/members/oscar.jpeg" },
  { name: "Renata Martinez Camargo", title: "Member", image: "/members/renata.png" },
  { name: "Ria Tao", title: "Member", image: "/members/ria.jpg" },
  { name: "Riana Mistry", title: "Member", image: "/members/riana.png" },
  { name: "Rijul Garg", title: "Member", image: "/members/rijul.png" },
  { name: "Sanjay Sundaram", title: "Member", image: "/members/sanjay.png" },
  { name: "Sarah Zong", title: "Member", image: "/members/sarah.jpeg" },
  { name: "Shweta Surendar", title: "Member", image: "/members/shweta.jpg" },  
  { name: "Tina Ye", title: "Member", image: "/members/tina.jpg" },
  { name: "Valerie Eng", title: "Member", image: "/members/valerie.png" },
  { name: "Winston Luo", title: "Member", image: "/members/winston.jpeg" },
  { name: "Yale Tsai", title: "Member", image: "/members/yale.jpeg" }
]
