import { Member } from '../types/members'

export const members: Member[] = [
  //updated for fa26
  { name: "Aiji Li", title: "Member", image: "/exec/aiji.png" },
  { name: "Alp Senay", title: "Member", image: "/members/alp.jpg" },
  { name: "Andrew Falcom", title: "Member", image: "/members/andrew.png" },
  { name: "Angad Singh Josan", title: "Member", image: "/members/angad.jpg" },
  { name: "Angie Wibowo", title: "Member", image: "/members/angie-wibowo.jpg" },
  { name: "Angie Zhu", title: "Member", image: "/members/angie.png" },
  { name: "Ashley Huang", title: "Member", image: "/members/ashley.png" },
  { name: "Caden Kelly", title: "Member", image: "/members/caden.jpg" },
  { name: "Cathryn Chang", title: "Member", image: "/members/cathryn.jpeg" },
  { name: "Daniel Gil", title: "Member", image: "/exec/daniel.jpg" },
  { name: "Dylan Dang", title: "Member", image: "/members/dylan.png" },
  { name: "Edan Gortzak", title: "Member", image: "/members/edan.png" },
  { name: "Emma Feth", title: "Member", image: "/exec/emma.jpg" },
  { name: "Evan Johnson", title: "Member", image: "/members/evan.png" },
  { name: "Henry Bonomolo", title: "Member", image: "/project-managers/henry.jpeg" },
  { name: "Irene Chung", title: "Member", image: "/members/irene.jpg" },
  { name: "Iris Li", title: "Member", image: "/members/iris.jpg" },
  { name: "Jennifer Cheng", title: "Member", image: "/members/jennifer.jpeg" },
  { name: "Jessie Wang", title: "Member", image: "/members/jessie.jpg" },
  { name: "Jesslyn Ashley Ruswan", title: "Member", image: "/members/jesslyn.jpeg" },
  { name: "Joey Wong", title: "Member", image: "/members/joey.png" },
  { name: "Julia Duan", title: "Member", image: "/members/julia.png" },
  { name: "Kathy Yun", title: "Member", image: "/members/kathy.jpeg" },
  { name: "Landy Manzanero", title: "Member", image: "/members/landy.JPEG" },
  { name: "Lara Chieppe", title: "Member", image: "/members/lara.jpg" },
  { name: "Mandy Pham", title: "Member", image: "/members/mandy.jpeg" },
  { name: "Martin Park", title: "Member", image: "/members/martin.jpg" },
  { name: "Naila Talib", title: "Member", image: "/members/naila.jpg" },
  { name: "Nathan Ye", title: "Member", image: "/members/nathan.jpeg" },
  { name: "Nitya Kuppireddy", title: "Member", image: "/exec/nitya.jpg" },
  { name: "Nomin-Erdene Batchuluun", title: "Member", image: "/members/nomi.jpeg" },
  { name: "Oscar Zhang", title: "Member", image: "/members/oscar.jpeg" },
  { name: "Owen Hughes", title: "Member", image: "/members/owen.jpg" },
  { name: "Pavithra Arun Anand", title: "Member", image: "/members/pavithra.jpg"},
  { name: "Rafael Mojica", title: "Member", image: "/members/rafael.jpg" },
  { name: "Renata Martinez Camargo", title: "Member", image: "/members/renata.png" },
  { name: "Rijul Garg", title: "Member", image: "/members/rijul.png" },
  { name: "Ronit Mathur", title: "Member", image: "/members/ronit.jpg" },
  { name: "Sanjay Sundaram", title: "Member", image: "/members/sanjay.png" },
  { name: "Shweta Surendar", title: "Member", image: "/members/shweta.jpg" },
  { name: "Sodbayar Ganbat", title: "Member", image: "/exec/sod.jpeg" },
  { name: "Valerie Eng", title: "Member", image: "/members/valerie.png" },
  { name: "Winston Luo", title: "Member", image: "/members/winston.jpeg" },
  { name: "Yale Tsai", title: "Member", image: "/members/yale.jpeg" }
]
